spring.application.name=pawsy
server.port=8080
logging.level.org.springframework.web.client.RestClient=DEBUG
spring.thymeleaf.cache=false

user.service.url=${USER_SERVICE_URL}
pet.service.url=${PET_SERVICE_URL}
adoption.service.url=${ADOPTION_SERVICE_URL}