spring.application.name=pawsy
spring.profiles.active=dev

spring.security.user.name=${SECRET_USER}
spring.security.user.password=${SECRET_PASSWORD}
spring.security.user.roles=${SECRET_ROLE}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# spring.thymeleaf.cache=false
