apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pawsy
  template:
    metadata:
      labels:
        app: pawsy
    spec:
      containers:
        - name: pawsy
          image: pawsy
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pawsy-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2