apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <replace-with-password>
  MYSQL_PASSWORD: <replace-with-password>
  MYSQL_HOST: <replace-with-host>
  MYSQL_USER: <replace-with-user>